join method
mate-academy/js_array-method-join pull request #1287
Opened 2022-06-07 19:46 UTC by NikitaKarbazin

2022-06-07 19:55 UTC, Kaunin1 approved these changes
Solution looks fine

2022-06-08 09:46 UTC, illiarerun requested changes
GJ, let's work on fixes now:

2022-06-08 09:46 UTC, illiarerun commented on src/arrayMethodJoin.js
> +        resultJoin += `${separator}`;
no need for extrapolation here
```suggestion
        resultJoin += separator;
```

2022-06-08 09:46 UTC, illiarerun commented on src/arrayMethodJoin.js
> +      next = elem === null || elem === undefined ? '' : elem;
format ternaries properly, don't write them in one line
```suggestion
      next = elem === null || elem === undefined 
        ? '' 
        : elem;
```

2022-06-08 09:46 UTC, illiarerun commented on src/arrayMethodJoin.js
> +      next = elem === null || elem === undefined ? '' : elem;
you also don't need a let here, make it a const and set value instantly
```suggestion
      const next = ...
```

2022-06-08 09:46 UTC, illiarerun commented on src/arrayMethodJoin.js
> +source.join(null);
remove test code
```suggestion
```

2022-06-08 09:46 UTC, illiarerun commented on src/arrayMethodJoin.js
> +      resultJoin += `${next}`;
no interpolation here, also
```suggestion
      resultJoin += next;
```

2022-06-08 10:14 UTC, illiarerun approved these changes

2023-10-07 15:40 UTC, closed without merging