Solution
mate-academy/js_array-method-join pull request #1489
Opened 2022-08-13 20:12 UTC by ostUp

2022-08-15 12:20 UTC, Jamal-Amoian approved these changes
Perfectly!

2022-08-15 12:22 UTC, Jamal-Amoian requested changes

2022-08-15 12:22 UTC, Jamal-Amoian commented on src/arrayMethodJoin.js
> +    let res = '';
You should to choose more logical name for your variable

2022-08-16 06:42 UTC, AlinaMatuschak approved these changes

2022-08-16 06:42 UTC, AlinaMatuschak commented on src/arrayMethodJoin.js
> +    let res = '';
What is res? 🙃

2023-03-22 18:04 UTC, closed without merging