Solution
mate-academy/js_array-method-join pull request #1673
Opened 2022-09-30 13:11 UTC by Ivanenko1402

2022-10-02 11:48 UTC, SanyaBratashchuk requested changes

2022-10-02 11:48 UTC, SanyaBratashchuk commented on src/arrayMethodJoin.js
> +      }
what 
```suggestion
```

2022-10-02 11:48 UTC, SanyaBratashchuk commented on src/arrayMethodJoin.js
> +      }
```suggestion
      if (this[i] !== undefined && this[i] !== null) {
        result += this[i]
      }
```

2022-10-02 11:48 UTC, SanyaBratashchuk commented on src/arrayMethodJoin.js
> +    }
```suggestion
      if (i !== this.length - 1) {
        result += separator;
      }
    }
```

2022-10-04 14:20 UTC, liliia-livandovskaya approved these changes

2026-03-02 13:24 UTC, closed without merging