All Done
mate-academy/js_array-method-join pull request #1789
Opened 2022-11-22 12:31 UTC by SalehBUD

2022-11-24 13:19 UTC, mgrinko requested changes

2022-11-24 13:19 UTC, mgrinko commented on src/arrayMethodJoin.js
> +    const sep = separator !== undefined ? separator : ',';
set the default value to the function parameter instead

2022-11-24 13:19 UTC, mgrinko commented on src/arrayMethodJoin.js
> +    const arr = [...this];
why do you copy the array?

2022-11-24 13:19 UTC, mgrinko commented on src/arrayMethodJoin.js
> +    res = res.substring(0, res.length - String(sep).length);
do you really needed to add a separator after the last element?

2022-11-24 13:19 UTC, mgrinko commented on src/arrayMethodJoin.js
> +      res += sep;
One blank line between a block and the next command
```suggestion
      }
      
      res += sep;
```

2022-11-24 13:19 UTC, mgrinko commented on src/arrayMethodJoin.js
> +        && arr[i] !== undefined
Do you really need all these conditions?

2022-11-29 13:03 UTC, dahimohamed approved these changes
good job

2022-11-29 13:13 UTC, naziamoff approved these changes

2022-11-29 13:13 UTC, naziamoff commented on src/arrayMethodJoin.js
> +    const sep = separator;
do you need this variable here? It basically does the same thing as the function parameter

2026-08-05 04:35 UTC, closed without merging