solution_1
mate-academy/js_array-method-join pull request #1951
Opened 2023-01-02 14:54 UTC by Borys-Andrew

2023-01-02 23:11 UTC, nzrii-kysel requested changes

2023-01-02 23:11 UTC, nzrii-kysel commented on src/arrayMethodJoin.js
> +    }
`join` should not mutate original array

2023-01-02 23:11 UTC, nzrii-kysel commented on src/arrayMethodJoin.js
> +      }
you do `result += this[i]` in both cases, better take it out of the `if` statement

2023-01-04 06:13 UTC, Anna-Tkachenko requested changes

2023-01-04 06:13 UTC, Anna-Tkachenko commented on src/arrayMethodJoin.js
> +      }
let's add the item to the result string only if it's not empty or undefined instead of setting empty string to the element

2023-01-04 06:13 UTC, Anna-Tkachenko commented on src/arrayMethodJoin.js
> +    }
it's not clear why did you set this check
for what reason did you check the last element of the array?

2023-01-04 06:13 UTC, Anna-Tkachenko commented on src/arrayMethodJoin.js
> +    const copy = [...this];
for what reason did you make the copy of current array?
check do you really need it

2025-05-01 20:21 UTC, closed without merging