Develop
mate-academy/js_array-method-join pull request #2367
Opened 2023-05-10 11:40 UTC by serentinos

2023-05-10 18:18 UTC, skinnyjazz reviewed
It looks nice, but there shouldn't be any commented code.

2023-05-10 21:01 UTC, AleksandrTsivilin approved these changes
Good job!!

2023-05-11 07:44 UTC, 33Orange requested changes
Good job 🔥 

Don't forget to check the code and remove useless comments, console.log, etc.

2023-05-11 07:44 UTC, 33Orange commented on src/arrayMethodJoin.js
> +
Delete comments

2023-05-11 07:44 UTC, 33Orange commented on src/arrayMethodJoin.js
> +      };
Remove the unnecessary semicolon after the closing brace of the if statement.

2023-05-11 07:44 UTC, 33Orange commented on src/arrayMethodJoin.js
> +// applyCustomJoin();
Remove the commented-out code or provide a meaningful comment explaining its purpose.

2023-05-11 07:44 UTC, 33Orange commented on src/arrayMethodJoin.js
> +// ['test', 'test'].join2('--');
Remove the commented-out code or provide a meaningful comment explaining its purpose.

2023-05-11 07:44 UTC, 33Orange commented on src/arrayMethodJoin.js
> +  [].__proto__.join2 = function(separator = ',') {
Avoid extending the built-in Array prototype. Instead, create a new function that takes array as a parameter.

2023-05-11 07:44 UTC, 33Orange commented on src/arrayMethodJoin.js
> +      };
Remove the unnecessary semicolon after the closing brace of the if statement.

2023-05-12 06:32 UTC, Anna-Tkachenko approved these changes

2023-08-14 11:54 UTC, closed without merging