solution
mate-academy/js_array-method-join pull request #2414
Opened 2023-05-15 17:14 UTC by Vo7kov

2023-05-15 18:26 UTC, Viktor-Kost requested changes

2023-05-15 18:26 UTC, Viktor-Kost commented on src/arrayMethodJoin.js
> +      divider = ',';
This condition is redundant, as the default value for 'separator' has already been set in the function definition. You can remove lines 11-15.

2023-05-15 18:26 UTC, Viktor-Kost commented on src/arrayMethodJoin.js
> +        result += String(this[i]);
```suggestion
        result += this[i];
```

2023-05-15 18:26 UTC, Viktor-Kost commented on src/arrayMethodJoin.js
> +    let divider = separator;
redundant variable. You can use separator directly at 19 line

2023-05-16 07:18 UTC, etojeDenys approved these changes
awesome

2025-07-07 14:18 UTC, closed without merging