code
mate-academy/js_array-method-join pull request #2483
Opened 2023-06-13 16:17 UTC by DanielLinker17

2023-06-13 18:21 UTC, SanyaBratashchuk requested changes

2023-06-13 18:21 UTC, SanyaBratashchuk commented on src/arrayMethodJoin.js
> +      }
```suggestion
      if (this[i] !== null && this[i] !== undefined) {
        result += this[i];
      } 
```

2023-06-13 19:13 UTC, DanielLinker17 commented on src/arrayMethodJoin.js
> +      }
dosen't pass tests after this change

2023-06-14 08:00 UTC, DarkMistyRoom approved these changes
Good job!

2025-07-29 00:29 UTC, closed without merging