solution
mate-academy/js_array-method-join pull request #343
Opened 2020-09-24 15:43 UTC by andlap24

2020-09-24 17:21 UTC, goncharukop approved these changes

2020-09-25 07:31 UTC, solaryasha requested changes, later dismissed

2020-09-25 07:31 UTC, solaryasha commented on src/arrayMethodJoin.js
> +    let output = '';
Ненайкраща назва змінної. Що повертає метод join ?

2020-09-25 18:10 UTC, andlap24 commented on src/arrayMethodJoin.js
> +    let output = '';
повертає string з поєднаними елементами массива. Зараз покумекаю над назвою іншою. output як з початку обявив, щоб не плутатись, так і не змінив у кінці.

2020-09-28 08:02 UTC, Vladimir-Beliy approved these changes

2020-09-28 08:02 UTC, Vladimir-Beliy commented on src/arrayMethodJoin.js
> +    let newString = '';
```suggestion
    let result = '';
```

2020-09-29 07:14 UTC, Vladimir-Beliy approved these changes

2026-02-15 13:07 UTC, closed without merging