added solution
mate-academy/js_array-method-join pull request #412
Opened 2020-12-15 12:02 UTC by MarchD

2020-12-15 12:24 UTC, olesiatk approved these changes

2020-12-15 12:53 UTC, aionova requested changes

2020-12-15 12:53 UTC, aionova commented on src/arrayMethodJoin.js
> +        this[i] = '';
You mutate the original array here and you shouldn't

2020-12-16 08:10 UTC, aionova approved these changes
Good job!

2020-12-16 08:10 UTC, aionova commented on src/arrayMethodJoin.js
> +    const array = [...this];
No need to include data type in the name of a variable. We know that it's an array. 
```suggestion
    const elements = [...this];
```

2020-12-16 08:10 UTC, aionova commented on src/arrayMethodJoin.js
> +      joinedElements = joinedElements + array[i] + separator;
```suggestion
      joinedElements += array[i] + separator;
```

2024-01-08 06:52 UTC, closed without merging