Kisilov-Vadim
mate-academy/js_array-method-join pull request #92
Opened 2019-10-02 17:25 UTC by Kisilov-Vadim

2019-10-04 09:34 UTC, 8hokage requested changes

2019-10-04 09:34 UTC, earthhuman41 commented on src/arrayMethodJoin.js
> +    || typeof sep === 'object') {
Слишком много проверок, почему бы просто не приводить к строке.

2019-10-07 14:21 UTC, gestap commented on src/arrayMethodJoin.js
>    [].__proto__.join2 = function(separator) {
you can add a default value for separator
```suggestion
  [].__proto__.join2 = function(separator = ',') {
```

2019-10-07 14:28 UTC, ost-ptk approved these changes

2023-07-08 18:48 UTC, closed without merging