Finally done
mate-academy/js_array-method-join pull request #947
Opened 2021-12-14 13:13 UTC by MaksimusCRS

2021-12-14 13:32 UTC, Oleksandr-Leshchenko requested changes

2021-12-14 13:32 UTC, Oleksandr-Leshchenko commented on src/arrayMethodJoin.js
> +    return str;
Мать моя женщина, какой кошмар. Весь код можно уместить в строчек 15. К тому же, по условию нельзя писать лупы в ифах

2021-12-14 13:33 UTC, MaksimusCRS commented on src/arrayMethodJoin.js
> +    return str;
Он меня доконал просто, постоянно не проходил этот 1 тест с separator = 'null', поэтому я его решил тупо в лоб)

2021-12-14 13:58 UTC, Oleksandr-Leshchenko commented on src/arrayMethodJoin.js
> +    return str;
)

2021-12-14 13:58 UTC, Oleksandr-Leshchenko approved these changes

2021-12-17 19:23 UTC, Denchepornyuk approved these changes

2022-10-20 17:53 UTC, closed without merging